### ISSUE TITLE
Implement way to set date/time for testing to enable robust test coverage related to dates & times

### ISSUE THREAD

**Issue by fredciaramaglia** [ShelterTechSF/askdarcel-web#762] opened 2019-05-23 23:39 UTC
It would be extremely useful to have a way for QA to set the date and time in the app to enable robust test coverage related to dates & times.  For example, part of the plan might say:  between 9pm and midnight on a Friday, run the following tests.

**Comment by richardxia** [comment] 2019-07-01 14:51
This isn't really possible because the application doesn't have an internal time. All times come from the user's browser. You should be able to achieve this by setting your computer's clock. Is that sufficient?

**Comment by richardxia** [comment] 2019-09-22 03:04
I can confirm that I have been able to change my computer's clock and test out various scenarios. I'm going to close this out.

**Closed by richardxia** 2019-09-22 03:04 UTC

**Comment by Maxastuart** [comment] 2019-09-22 15:52
In addition, it may be possible to schedule certain tests to run at certain
times of the day, I'm thinking of exploring GitHub Actions for this
