### ISSUE TITLE
"Save" button should always be visible on the left hand side of the edit screen

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#800] opened 2019-07-14 20:34 UTC
Currently, the "Save" button on the edit screen is anchored to the bottom -- the user must scroll all the way down to access it. The "Save" button should instead always be visible.

**Comment by Maxastuart** [comment] 2019-07-19 19:31
Duplicate of #755

**Closed by Maxastuart** 2019-07-19 19:31 UTC
Labels: First-Time Friendly, HAP
