### ISSUE TITLE
Admin panel refactor

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#316] opened 2017-10-08 03:35 UTC
Resurrect the admin panel and make it more usable. @lexholden to provide details.

**Comment by alexanderturinske** [comment] 2017-11-16 03:25
Duplicate of #280 ?

**Comment by lexholden** [comment] 2017-11-16 06:50
@alexanderturinske This is the broader epic for the pull #280, there are still outstanding issues - install ZenHub and you can see them.

**Comment by alexanderturinske** [comment] 2017-11-16 14:28
@lexholden Ah; I understand. Thank you!

**Comment by lexholden** [comment] 2017-12-10 01:20
Closing this, the merged version satisfies this requirement. Will create separate subissues for the enhancements flagged up in #325

**Closed by lexholden** 2017-12-10 01:20 UTC
Labels: Epic
