### ISSUE TITLE
'Manage Folders' Modal UI

### ISSUE THREAD

**Issue by katerina-kossler** [ShelterTechSF/askdarcel-web#1335] opened 2024-04-09 20:33 UTC
**Acceptance:** `Manage Folders` modal from the dashboard where a user can change the order of Folders or create a new folder

**Design notes:** [figma](https://www.figma.com/file/XUttHGa1csIpbSiurbYmjo/Case-Worker?type=design&node-id=7714-4087&mode=design&t=aDIcinPiOvaunEkn-0)

**Comment by richardxia** [comment] 2024-07-14 01:29
Closing this as a duplicate of https://github.com/ShelterTechSF/askdarcel-web/issues/1323

**Closed by richardxia** 2024-07-14 01:29 UTC
