### ISSUE TITLE
Delete button for schedule days does not work

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#693] opened 2019-04-07 21:27 UTC
When there are multiple open and close times for a single day, a red delete icon appears next to the second. Clicking the icon causes the second open and close time to disappear, but clicking save changes does not cause the date to be deleted from the db.![Screen Shot 2019-04-07 at 2.26.58 PM.png](https://images.zenhubusercontent.com/56e745406caf56c9d38dbb89/22fa0ea2-9ccc-48e3-81d3-27dd269cd71d)

**Comment by tsyaeger** [comment] 2019-04-08 00:08
Is this related to issue 392? This is a previous commit that deletes schedule_day from the DB but it uses just the old cols at the moment. https://github.com/ShelterTechSF/askdarcel-api/commit/47717a3ee76a7c98a979e6f9898de367a5b52e6b

**Comment by cliffcrosland** [comment] 2019-04-08 04:16
@tsyaeger @jjfreund - I was unable to reproduce this in local dev env nor on staging. Haven't tried production though. Perhaps recent changes have fixed this already?

For what it's worth, I tried adding a second open-time for a few days for this resource: https://staging.askdarcel.org/resource/edit?resourceid=75. I was able to add and delete them correctly, and `Save Changes` respected those changes.

**Comment by Maxastuart** [comment] 2019-04-13 05:41
Can anyone reproduce this? Is it only happening on the ones with `nil` values in the database @jjfreund ?

**Comment by tsyaeger** [comment] 2019-04-15 23:10
@Maxastuart @cliffcrosland @jjfreund  Just noticed that the 392 fix (above) was merged, so apparently that took care of this issue.

**Comment by jjfreund** [comment] 2019-04-15 23:14
I assume we have to clean out the nil values -- I can do that directly in prod, then we can call the issue done.

**Comment by tsyaeger** [comment] 2019-04-15 23:21
Cool. I haven't touched the nil values. If you have the chance, could you share the gist of your process for cleaning out the nils? I'm just curious about how that is safely done in production. I have no experience with it.

**Closed** 2019-05-02 03:07 UTC
Labels: HAP, Urgent, bug
