### ISSUE TITLE
Improve Search Front End (Filters)

### ISSUE THREAD

**Issue by Maxastuart** [ShelterTechSF/askdarcel-web#685] opened 2019-03-30 22:34 UTC
Search Filtering Requirements Doc: 
https://sheltertech.quip.com/WCg2AYLSGVOQ/Search-Filtering-Requirements-Doc 

Mockup: 
https://www.figma.com/file/H0kD6ZZPhPR2RMyNJHWWeTtI/Web-Client?node-id=0%3A1

**Comment by quanhuynh** [comment] 2019-06-02 20:00
duplicate with #736

**Comment by jjfreund** [comment] 2019-06-15 21:44
Dupe of 736

**Closed** 2019-06-15 21:45 UTC
Labels: Epic
